#!/usr/bin/env bash
#
# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
#
# Build Ferrocene from source at a specific commit and package it as a Bazel-friendly archive.
#
# Example:
#   ./scripts/build_ferrocene.sh --sha <commit> --target x86_64-unknown-linux-gnu
#
set -euo pipefail

REPO_URL=${FERROCENE_REPO_URL:-"https://github.com/ferrocene/ferrocene.git"}
SRC_DIR=${FERROCENE_SRC_DIR:-".cache/ferrocene-src"}
OUT_DIR=${FERROCENE_OUT_DIR:-"out/ferrocene"}

TARGET_TRIPLE="x86_64-unknown-linux-gnu"
EXEC_TRIPLE="x86_64-unknown-linux-gnu"
FERROCENE_SHA="${FERROCENE_SHA:-}"
JOBS="${FERROCENE_JOBS:-}"
BOOTSTRAP_TOML="${FERROCENE_BOOTSTRAP_TOML:-}"
DIST_PACKAGES="${FERROCENE_DIST_PACKAGES:-rustc rust-std cargo rustfmt clippy}"
INSTALL_PACKAGES="${FERROCENE_INSTALL_PACKAGES:-rustc library/std cargo rustfmt clippy}"
GIT_DEPTH="${FERROCENE_GIT_DEPTH:-1}"

usage() {
  cat <<'EOF'
Build Ferrocene and emit a tar.gz ready for the ferrocene_toolchain.bzl module extension.

Required:
  --sha <commit>          Commit or tag to check out (FERROCENE_SHA)

Optional:
  --target <triple>       Target triple to build (default: x86_64-unknown-linux-gnu)
  --exec <triple>         Exec/host triple (default: x86_64-unknown-linux-gnu)
  --repo-url <url>        Git repo to clone (default: https://github.com/ferrocene/ferrocene.git)
  --src-dir <path>        Cache directory for the git checkout (default: .cache/ferrocene-src)
  --out-dir <path>        Output directory for artifacts (default: out/ferrocene)
  --jobs <n>              Parallel jobs passed to x.py (-j)
  --bootstrap <path>      Path to write bootstrap.toml (default: <src-dir>/bootstrap.toml)
  --dist-packages "<pkgs>" Space-separated list of dist/install packages (default: "rustc rust-std cargo rustfmt clippy")
  --install-packages "<pkgs>" Space-separated list of install packages (default: "rustc library/std cargo rustfmt clippy")
  --git-depth <n>         Git clone/fetch depth (default: 1). Use 0 for full history.
  --full                  Alias for --git-depth 0

Environment overrides:
  FERROCENE_REPO_URL, FERROCENE_SRC_DIR, FERROCENE_OUT_DIR, FERROCENE_SHA, FERROCENE_JOBS,
  FERROCENE_BOOTSTRAP_TOML, FERROCENE_DIST_PACKAGES, FERROCENE_INSTALL_PACKAGES, FERROCENE_GIT_DEPTH
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --sha) FERROCENE_SHA="$2"; shift 2 ;;
    --target) TARGET_TRIPLE="$2"; shift 2 ;;
    --exec) EXEC_TRIPLE="$2"; shift 2 ;;
    --repo-url) REPO_URL="$2"; shift 2 ;;
    --src-dir) SRC_DIR="$2"; shift 2 ;;
    --out-dir) OUT_DIR="$2"; shift 2 ;;
    --jobs) JOBS="$2"; shift 2 ;;
    --bootstrap) BOOTSTRAP_TOML="$2"; shift 2 ;;
    --dist-packages) DIST_PACKAGES="$2"; shift 2 ;;
    --install-packages) INSTALL_PACKAGES="$2"; shift 2 ;;
    --git-depth) GIT_DEPTH="$2"; shift 2 ;;
    --full) GIT_DEPTH=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "${FERROCENE_SHA}" ]]; then
  echo "ERROR: --sha (or FERROCENE_SHA) is required." >&2
  usage
  exit 1
fi

if ! [[ "${GIT_DEPTH}" =~ ^[0-9]+$ ]]; then
  echo "ERROR: --git-depth must be a non-negative integer (0 for full history)." >&2
  exit 1
fi

for cmd in git python3; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: $cmd" >&2
    exit 1
  fi
done

if ! command -v uv >/dev/null 2>&1; then
  cat <<'EOF' >&2
Missing required command: uv
Ferrocene's bootstrap expects the `uv` package manager (https://github.com/astral-sh/uv) on PATH.
Install it (e.g., curl -LsSf https://astral.sh/uv/install.sh | sh) or provide a locally built binary.
EOF
  exit 1
fi

mkdir -p "${SRC_DIR}" "${OUT_DIR}"

if [[ ! -d "${SRC_DIR}/.git" ]]; then
  if [[ "${GIT_DEPTH}" -gt 0 ]]; then
    git clone --no-checkout --depth "${GIT_DEPTH}" "${REPO_URL}" "${SRC_DIR}"
  else
    git clone "${REPO_URL}" "${SRC_DIR}"
  fi
else
  git -C "${SRC_DIR}" remote set-url origin "${REPO_URL}"
fi

if [[ "${GIT_DEPTH}" -gt 0 ]]; then
  git -C "${SRC_DIR}" fetch --depth "${GIT_DEPTH}" origin "${FERROCENE_SHA}"
else
  git -C "${SRC_DIR}" fetch --all
fi
git -C "${SRC_DIR}" checkout --detach "${FERROCENE_SHA}"

BOOTSTRAP_TOML="${BOOTSTRAP_TOML:-${SRC_DIR}/bootstrap.toml}"
if [[ -f "${BOOTSTRAP_TOML}" ]]; then
  echo "Using existing ${BOOTSTRAP_TOML} (not overwriting)."
else
  cat > "${BOOTSTRAP_TOML}" <<EOF
# Auto-generated by build_ferrocene.sh to avoid CI artifact downloads and to target explicit triples.
change-id = "ignore"
profile = "dist"

[build]
host = ["${EXEC_TRIPLE}"]
target = ["${TARGET_TRIPLE}"]
extended = true

[llvm]
download-ci-llvm = false

[gcc]
download-ci-gcc = false

[rust]
download-rustc = false
EOF
  echo "Wrote ${BOOTSTRAP_TOML} (download-ci-llvm/gcc/rustc disabled)"
fi

J_FLAG=()
if [[ -n "${JOBS}" ]]; then
  J_FLAG=(-j "${JOBS}")
fi

CONFIG_FLAG=(--config "${BOOTSTRAP_TOML}")
DIST_ARGS=(${DIST_PACKAGES})
INSTALL_ARGS=(${INSTALL_PACKAGES})

python3 "${SRC_DIR}/x.py" "${J_FLAG[@]}" "${CONFIG_FLAG[@]}" dist --host "${EXEC_TRIPLE}" --target "${TARGET_TRIPLE}" "${DIST_ARGS[@]}"
rm -rf "${OUT_DIR}/install"
DESTDIR="${OUT_DIR}/install" python3 "${SRC_DIR}/x.py" "${J_FLAG[@]}" "${CONFIG_FLAG[@]}" install --host "${EXEC_TRIPLE}" --target "${TARGET_TRIPLE}" "${INSTALL_ARGS[@]}"

ARCHIVE_NAME="ferrocene-${FERROCENE_SHA}-${TARGET_TRIPLE}.tar.gz"
tar -C "${OUT_DIR}/install" -czf "${OUT_DIR}/${ARCHIVE_NAME}" .
sha256sum "${OUT_DIR}/${ARCHIVE_NAME}" | tee "${OUT_DIR}/${ARCHIVE_NAME}.sha256"

cat <<EOF

Built archive: ${OUT_DIR}/${ARCHIVE_NAME}
SHA256 file  : ${OUT_DIR}/${ARCHIVE_NAME}.sha256

Pass the archive URL and SHA256 to the ferrocene_toolchain.bzl module extension.
EOF
